### PR TITLE
fix two functions for pointer used as iterator

### PR DESCRIPTION
**Pull request by starius**

### CODE REVIEW

**Comment by jviiret** [comment]
Hi starius,

Can you give us a description? Did you encounter a build/platform problem that motivated this PR?

**Comment by starius** [comment]
In general, an iterator [can](http://www.cplusplus.com/reference/iterator/) be a pointer:

> The most obvious form of iterator is a pointer: A pointer can point to elements in an array, and can iterate through them using the increment operator (++).

In particular, `std::vector<T>::iterator` is implementation-defined [random access iterator](http://en.cppreference.com/w/cpp/concept/RandomAccessIterator). The definition of a random access iterator does not mention `iterator::value_type`. A raw pointer meets all the requirements to a random access iterator.

Despite the fact that [several reasons](http://stackoverflow.com/a/32654648/1293417) exist not to use a raw pointer as an iterator, some implementation do it. I encountered a build problem and used this patch to prevent it. Current implementation of `iter_wrapper` and `add_to_engine_blob` relies on implementation details of some platforms (`iterator::value_type`). My implementation relies on `iterator_traits` which [provides](http://en.cppreference.com/w/cpp/iterator/iterator_traits) two partial specializations for pointer types T*, that is why my patch should work on any standards-compliant platform.

**Comment by jviiret** [comment]
What was the build problem you encountered with Hyperscan? Are you trying to port it to a system with an unusual STL?

**Comment by starius** [comment]
> What was the build problem you encountered with Hyperscan?

The build failed with the following error:

```
hyperscan/src/rose/rose_build_bytecode.cpp: In instantiation of 'u32 ue2::add_to_engine_blob(ue2::{anonymous}::build_context&, Iter, const Iter&)': with u32 = unsigned int; Iter = const mmbit_sparse_iter*
hyperscan/src/rose/rose_build_bytecode.cpp:2220:65:   required from here
hyperscan/src/rose/rose_build_bytecode.cpp:1227:49: error: 'const mmbit_sparse_iter*' is not a class, struct, or union type
     using value_type = typename Iter::value_type;
                                                 ^
hyperscan/src/rose/rose_build_bytecode.cpp:1245:26: error: 'const mmbit_sparse_iter*' is not a class, struct, or union type
     return verify_u32(rv);
                          ^
```

... and many similar errors.

> Are you trying to port it to a system with an unusual STL?

Yes. This STL is unusual in the way `std::vector<T>::iterator` is a pointer.

**Pull request merged**
